### ISSUE TITLE
上传文件的时候偶现崩溃

### ISSUE THREAD

**Issue by w653391491** [TencentCloud/cos-sdk-flutter-plugin#22]
java.lang.IllegalStateException: Null interceptor: [null, com.tencent.qcloud.core.http.interceptor.RetryInterceptor@f43b955, com.tencent.qcloud.core.http.HttpLoggingInterceptor@f0bff6a, com.tencent.qcloud.core.http.interceptor.RetryInterceptor@5ea3c5b, com.tencent.qcloud.core.http.interceptor.TrafficControlInterceptor@c819cf8]
 at okhttp3.OkHttpClient.verifyClientState(OkHttpClient.kt:248)
 at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:244)
 at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
 at com.tencent.qcloud.core.http.OkHttpClientImpl.init(OkHttpClientImpl.java:152)
 at com.tencent.qcloud.core.http.QCloudHttpClient.<init>(QCloudHttpClient.java:222)
 at com.tencent.qcloud.core.http.QCloudHttpClient.<init>(QCloudHttpClient.java:52)
 at com.tencent.qcloud.core.http.QCloudHttpClient$Builder.build(QCloudHttpClient.java:412)
 at com.tencent.cos.xml.CosXmlBaseService.setNetworkClient(CosXmlBaseService.java:237)
 at com.tencent.cos.xml.CosXmlBaseService.<init>(CosXmlBaseService.java:158)
 at com.tencent.cos.xml.CosXmlBaseService.<init>(CosXmlBaseService.java:132)
 at com.tencent.cos.xml.CosXmlSimpleService.<init>(CosXmlSimpleService.java:80)
 at com.tencent.cos.xml.CosXmlService.<init>(CosXmlService.java:243)
 at com.tencent.cos.flutter.plugin.CosPlugin.buildCosXmlService(CosPlugin.java:871)
 at com.tencent.cos.flutter.plugin.CosPlugin.access$100(CosPlugin.java:76)
 at com.tencent.cos.flutter.plugin.CosPlugin$1.run(CosPlugin.java:165)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668)
 at java.lang.Thread.run(Thread.java:1012)

**Comment by liangdy** [comment]
遇到同样的问题

**Comment by jordanqin** [comment]
从日志看是okhttp添加的拦截器都被置空了，但是cos sdk并没有该操作，且该问题为偶现，建议排查下APM、热修复等有没有在运行时通过反射等操作动态修改了代码。

okhttp库的issue下有类似的问题
https://github.com/square/okhttp/issues/4972
https://github.com/square/okhttp/issues/4579
